apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-workflow
spec:
  entrypoint: process-data
  templates:
    - name: process-data
      script:
        image: python:3.8
        command: ["python"]
        source: |
          with open("/scripts/process-data.py") as f:
              exec(f.read())
